version: '3.8'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    entrypoint: ["sh", "/app/entrypoint.sh"]
    volumes:
      - "./services/backend:/app"
      - "./services/backend/data/base_de_datos_chile.csv:/app/data/base_de_datos_chile.csv"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_dev
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - SECRET_KEY=secret
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5000
    volumes:
      - "./services/frontend:/usr/src/chat-app"
      - "/usr/src/chat-app/node_modules"
    depends_on:
      - backend
